### ISSUE TITLE
Bug no links das aulas

### ISSUE THREAD

**Issue by ReinanHS** [3dinvein/gdscript-basico-3.2#3]
Devido a migração para o Jekyll os links para as aulas no arquivo `README.md` ficaram desatualizados.  Em breve estarei enviando um Pull Request para solucionar esse problema e fechar essa Issue.

**Comment by 3dinvein** [comment]
Oi ReinanHS! Acho que corrigi o Issue que faltava, beleza. Que era o problema com os links. Obrigado!
